name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      environnement:
        description: "Environnement cible"
        type: choice
        options: [recette, production]
        default: recette
      message:
        description: "Message à afficher"
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test

      - name: Afficher les paramètres
        run: |
          echo "Environnement : ${{ inputs.environnement }}"
          echo "Message       : ${{ inputs.message }}"